name: macos-crontab-creation
uid: 6722b4ed-f891-4906-a4b2-f57762dfc72b
status: experimental
confidence: low
enabled: false
schedule: "0 */2 * * *"
queryEngine: opensearch.logs
publishers:
  - opensearch.signals
language: SQL
query: |
  SELECT DISTINCT
    DATE_FORMAT(timestamp, '%Y-%m-%dT%H:%i:%sZ') AS timestamp,
    CONCAT("process ", actor.process.file.path, " created/modified the file ", file.path) AS message,
    device.hostname,
    actor.user.name
  FROM macos-logs*
  WHERE file.path LIKE "/private/var/at/tabs/%"
    AND NOT actor.process.file.path = "/usr/bin/crontab"
    AND timestamp >= DATE_SUB(NOW(), INTERVAL 2 HOUR)
output:
  format: signal
  fields:
    - field: Timestamp
      source: timestamp
    - field: Message
      source: message
    - field: ResourceName
      source: device.hostname
    - field: ActorUserName
      source: actor.user.name
description:
  Suspicious CronTab Creation or Modification. Identifies attempts to
  create or modify a crontab via a process that is not crontab (i.e python,
  osascript, etc.).
references:
  - https://taomm.org/PDFs/vol1/CH%200x02%20Persistence.pdf
  - https://theevilbit.github.io/beyond/beyond_0004/
tags:
  - macos
author: adelka
ttps:
  - framework: MITRE ATT&CK
    tactic: Persistence
    name: "Scheduled Task/Job: Cron"
    id: T1053.003
    reference: https://attack.mitre.org/techniques/T1053/003/