- name: test-user-from-internal-ip
  when: |
    has(event.username) &&
    event.username == "test" &&
    has(event.ip_address) &&
    event.ip_address == "192.168.1.1"

- name: privileged-test-role
  when: |
    has(event.user_role) &&
    event.user_role in ["admin", "superuser"]
