extraVolumes:
  - name: clickhouse-tls
    secret:
      secretName: clickhouse-client-tls
extraVolumeMounts:
  - name: clickhouse-tls
    mountPath: /var/run/secrets/venator/clickhouse
    readOnly: true
