package slack

import (
	"bytes"
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"
	"time"

	"github.com/0x4D31/venator/internal/model"
)

const (
	defaultHTTPTimeout    = 15 * time.Second
	maxResponseSize       = 64 << 10
	maxErrorDetailSize    = 1024
	maxWebhookPayloadSize = 512 << 10
	defaultMaxFindings    = 20
)

type Client struct {
	WebhookURL  string
	httpClient  *http.Client
	maxFindings int
}

type webhookPayload struct {
	Text        string              `json:"text"`
	Attachments []webhookAttachment `json:"attachments"`
	Username    string              `json:"username"`
	IconEmoji   string              `json:"icon_emoji"`
	Markdown    bool                `json:"mrkdwn"`
}

type webhookAttachment struct {
	Fallback string `json:"fallback"`
	Title    string `json:"title"`
	Text     string `json:"text"`
	Color    string `json:"color"`
}

func New(ctx context.Context, cfg Config) (*Client, error) {
	if err := ctx.Err(); err != nil {
		return nil, fmt.Errorf("create Slack connector: %w", err)
	}
	webhookURL := strings.TrimSpace(cfg.WebhookURL)
	parsedURL, err := url.Parse(webhookURL)
	if err != nil || parsedURL.Host == "" || (parsedURL.Scheme != "http" && parsedURL.Scheme != "https") {
		return nil, fmt.Errorf("invalid Slack webhook URL %q", cfg.WebhookURL)
	}
	if parsedURL.Scheme != "https" && parsedURL.Hostname() != "localhost" && parsedURL.Hostname() != "127.0.0.1" && parsedURL.Hostname() != "::1" {
		return nil, fmt.Errorf("slack webhook URL must use HTTPS (HTTP is allowed only on loopback)")
	}
	if cfg.MaxFindings == 0 {
		cfg.MaxFindings = defaultMaxFindings
	}
	if cfg.MaxFindings < 1 || cfg.MaxFindings > 50 {
		return nil, fmt.Errorf("slack maxFindings must be between 1 and 50")
	}
	return &Client{
		WebhookURL: webhookURL,
		httpClient: &http.Client{
			Timeout:       defaultHTTPTimeout,
			CheckRedirect: func(*http.Request, []*http.Request) error { return http.ErrUseLastResponse },
		},
		maxFindings: cfg.MaxFindings,
	}, nil
}

func (c *Client) Publish(ctx context.Context, batch model.PublishBatch) error {
	if len(batch.Findings) == 0 {
		return nil
	}
	if len(batch.Findings) > c.maxFindings {
		return fmt.Errorf("slack batch has %d findings; configured limit is %d", len(batch.Findings), c.maxFindings)
	}

	payload, err := buildWebhookPayload(ctx, batch)
	if err != nil {
		return err
	}
	payloadBytes, err := json.Marshal(payload)
	if err != nil {
		return fmt.Errorf("marshal Slack webhook payload: %w", err)
	}
	if len(payloadBytes) > maxWebhookPayloadSize {
		return fmt.Errorf("slack webhook payload is %d bytes; limit is %d", len(payloadBytes), maxWebhookPayloadSize)
	}

	req, err := http.NewRequestWithContext(ctx, http.MethodPost, c.WebhookURL, bytes.NewReader(payloadBytes))
	if err != nil {
		return fmt.Errorf("create Slack webhook request: %w", err)
	}
	req.Header.Set("Content-Type", "application/json")
	req.Header.Set("Accept", "text/plain")

	resp, err := c.httpClient.Do(req)
	if err != nil {
		if ctxErr := ctx.Err(); ctxErr != nil {
			return fmt.Errorf("send Slack webhook: %w", ctxErr)
		}
		var urlErr *url.Error
		if errors.As(err, &urlErr) {
			return fmt.Errorf("send Slack webhook: %w", urlErr.Err)
		}
		return fmt.Errorf("send Slack webhook failed")
	}
	body, readErr := io.ReadAll(io.LimitReader(resp.Body, maxResponseSize))
	closeErr := resp.Body.Close()
	if readErr != nil {
		return errors.Join(fmt.Errorf("read Slack webhook response: %w", readErr), closeErr)
	}
	if closeErr != nil {
		return fmt.Errorf("close Slack webhook response: %w", closeErr)
	}
	if resp.StatusCode < http.StatusOK || resp.StatusCode >= http.StatusMultipleChoices {
		detail := safeErrorDetail(body)
		if detail == "" {
			detail = http.StatusText(resp.StatusCode)
		}
		return fmt.Errorf("slack webhook returned %s: %s", resp.Status, detail)
	}

	return nil
}

func buildWebhookPayload(ctx context.Context, batch model.PublishBatch) (webhookPayload, error) {
	attachments := make([]webhookAttachment, 0, len(batch.Findings))
	for i, finding := range batch.Findings {
		if err := ctx.Err(); err != nil {
			return webhookPayload{}, err
		}
		canonicalJSON, err := json.Marshal(finding)
		if err != nil {
			return webhookPayload{}, fmt.Errorf("marshal Slack finding %d (%q): %w", i, finding.ID, err)
		}

		title := finding.Rule.Name
		if title == "" {
			title = "Venator finding"
		}
		attachments = append(attachments, webhookAttachment{
			Fallback: fmt.Sprintf("Venator finding %s", finding.ID),
			Title:    sanitizePlainText(title),
			Text:     string(canonicalJSON),
			Color:    "danger",
		})
	}

	ruleName := batch.Rule.Name
	if ruleName == "" && len(batch.Findings) > 0 {
		ruleName = batch.Findings[0].Rule.Name
	}
	if ruleName == "" {
		ruleName = "unknown"
	}
	return webhookPayload{
		Text:        fmt.Sprintf("%d finding(s) generated by %s.", len(batch.Findings), sanitizePlainText(ruleName)),
		Attachments: attachments,
		Username:    "venator",
		IconEmoji:   ":bow_and_arrow:",
		Markdown:    false,
	}, nil
}

func safeErrorDetail(body []byte) string {
	if len(body) > maxErrorDetailSize {
		body = body[:maxErrorDetailSize]
	}
	return strings.TrimSpace(strings.Map(func(r rune) rune {
		if r < 0x20 || r == 0x7f {
			return ' '
		}
		return r
	}, string(body)))
}

func sanitizePlainText(value string) string {
	return strings.TrimSpace(strings.Map(func(r rune) rune {
		if r < 0x20 || r == 0x7f {
			return ' '
		}
		return r
	}, value))
}
