apiVersion: v1
kind: ConfigMap
metadata:
  name: global-config
  labels:
    app.kubernetes.io/name: venator
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
data:
  global_config.yaml: |-
{{ .Files.Get "files/global_config.yaml" | indent 4 }}
