{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ default (printf "%s-venator" .Release.Name) .Values.serviceAccount.name | quote }}
  labels:
    app.kubernetes.io/name: venator
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccount.automountServiceAccountToken }}
{{- end }}
